/* Generated By:JJTree: Do not edit this line. ASTLogicalWindow.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public
class ASTLogicalWindow extends SimpleNode {
  public ASTLogicalWindow(int id) {
    super(id);
  }

  public ASTLogicalWindow(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e6caf8779a8193d1b075740ebbe89c30 (do not edit this line) */
