/* Generated By:JJTree: Do not edit this line. ASTPhysicalWindow.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public
class ASTPhysicalWindow extends SimpleNode {
  public ASTPhysicalWindow(int id) {
    super(id);
  }

  public ASTPhysicalWindow(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=450adf9f754cf055f613e5f1dd7a7159 (do not edit this line) */
