/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 6.0_1 */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTUPDATESEQUENCE = 0;
  public int JJTUPDATECONTAINER = 1;
  public int JJTQUERYCONTAINER = 2;
  public int JJTVOID = 3;
  public int JJTBASEDECL = 4;
  public int JJTPREFIXDECL = 5;
  public int JJTSELECTQUERY = 6;
  public int JJTFROMNAMEDWINDOW = 7;
  public int JJTWINDOW = 8;
  public int JJTTIMEUNIT = 9;
  public int JJTWINDOWOVERLAP = 10;
  public int JJTLOGICALWINDOW = 11;
  public int JJTPHYSICALWINDOW = 12;
  public int JJTSELECT = 13;
  public int JJTPROJECTIONELEM = 14;
  public int JJTCONSTRUCTQUERY = 15;
  public int JJTCONSTRUCT = 16;
  public int JJTDESCRIBEQUERY = 17;
  public int JJTDESCRIBE = 18;
  public int JJTASKQUERY = 19;
  public int JJTDATASETCLAUSE = 20;
  public int JJTWHERECLAUSE = 21;
  public int JJTWINDOWINWHERECLAUSE = 22;
  public int JJTBINDINGSCLAUSE = 23;
  public int JJTINLINEDATA = 24;
  public int JJTBINDINGSET = 25;
  public int JJTBINDINGVALUE = 26;
  public int JJTGROUPCLAUSE = 27;
  public int JJTORDERCLAUSE = 28;
  public int JJTGROUPCONDITION = 29;
  public int JJTHAVINGCLAUSE = 30;
  public int JJTORDERCONDITION = 31;
  public int JJTLIMIT = 32;
  public int JJTOFFSET = 33;
  public int JJTGRAPHPATTERNGROUP = 34;
  public int JJTBASICGRAPHPATTERN = 35;
  public int JJTOPTIONALGRAPHPATTERN = 36;
  public int JJTGRAPHGRAPHPATTERN = 37;
  public int JJTUNIONGRAPHPATTERN = 38;
  public int JJTMINUSGRAPHPATTERN = 39;
  public int JJTSERVICEGRAPHPATTERN = 40;
  public int JJTCONSTRAINT = 41;
  public int JJTFUNCTIONCALL = 42;
  public int JJTTRIPLESSAMESUBJECT = 43;
  public int JJTPROPERTYLIST = 44;
  public int JJTOBJECTLIST = 45;
  public int JJTTRIPLESSAMESUBJECTPATH = 46;
  public int JJTPROPERTYLISTPATH = 47;
  public int JJTPATHALTERNATIVE = 48;
  public int JJTPATHSEQUENCE = 49;
  public int JJTPATHELT = 50;
  public int JJTIRI = 51;
  public int JJTPATHONEINPROPERTYSET = 52;
  public int JJTPATHMOD = 53;
  public int JJTBLANKNODEPROPERTYLIST = 54;
  public int JJTCOLLECTION = 55;
  public int JJTVAR = 56;
  public int JJTOR = 57;
  public int JJTAND = 58;
  public int JJTCOMPARE = 59;
  public int JJTINFIX = 60;
  public int JJTMATH = 61;
  public int JJTNOT = 62;
  public int JJTNUMERICLITERAL = 63;
  public int JJTCOUNT = 64;
  public int JJTSUM = 65;
  public int JJTMIN = 66;
  public int JJTMAX = 67;
  public int JJTAVG = 68;
  public int JJTSAMPLE = 69;
  public int JJTGROUPCONCAT = 70;
  public int JJTMD5 = 71;
  public int JJTSHA1 = 72;
  public int JJTSHA224 = 73;
  public int JJTSHA256 = 74;
  public int JJTSHA384 = 75;
  public int JJTSHA512 = 76;
  public int JJTNOW = 77;
  public int JJTYEAR = 78;
  public int JJTMONTH = 79;
  public int JJTDAY = 80;
  public int JJTHOURS = 81;
  public int JJTMINUTES = 82;
  public int JJTSECONDS = 83;
  public int JJTTIMEZONE = 84;
  public int JJTTZ = 85;
  public int JJTRAND = 86;
  public int JJTABS = 87;
  public int JJTCEIL = 88;
  public int JJTFLOOR = 89;
  public int JJTROUND = 90;
  public int JJTSUBSTR = 91;
  public int JJTSTRLEN = 92;
  public int JJTUPPERCASE = 93;
  public int JJTLOWERCASE = 94;
  public int JJTSTRSTARTS = 95;
  public int JJTSTRENDS = 96;
  public int JJTSTRBEFORE = 97;
  public int JJTSTRAFTER = 98;
  public int JJTREPLACE = 99;
  public int JJTCONCAT = 100;
  public int JJTCONTAINS = 101;
  public int JJTENCODEFORURI = 102;
  public int JJTIF = 103;
  public int JJTIN = 104;
  public int JJTNOTIN = 105;
  public int JJTCOALESCE = 106;
  public int JJTSTR = 107;
  public int JJTLANG = 108;
  public int JJTLANGMATCHES = 109;
  public int JJTDATATYPE = 110;
  public int JJTBOUND = 111;
  public int JJTSAMETERM = 112;
  public int JJTISIRI = 113;
  public int JJTISBLANK = 114;
  public int JJTISLITERAL = 115;
  public int JJTISNUMERIC = 116;
  public int JJTBNODEFUNC = 117;
  public int JJTIRIFUNC = 118;
  public int JJTSTRDT = 119;
  public int JJTSTRLANG = 120;
  public int JJTUUID = 121;
  public int JJTSTRUUID = 122;
  public int JJTBIND = 123;
  public int JJTREGEXEXPRESSION = 124;
  public int JJTEXISTSFUNC = 125;
  public int JJTNOTEXISTSFUNC = 126;
  public int JJTRDFLITERAL = 127;
  public int JJTTRUE = 128;
  public int JJTFALSE = 129;
  public int JJTSTRING = 130;
  public int JJTQNAME = 131;
  public int JJTBLANKNODE = 132;
  public int JJTGRAPHREFALL = 133;
  public int JJTGRAPHORDEFAULT = 134;
  public int JJTUNPARSEDQUADDATABLOCK = 135;
  public int JJTQUADSNOTTRIPLES = 136;
  public int JJTLOAD = 137;
  public int JJTCLEAR = 138;
  public int JJTDROP = 139;
  public int JJTADD = 140;
  public int JJTMOVE = 141;
  public int JJTCOPY = 142;
  public int JJTCREATE = 143;
  public int JJTINSERTDATA = 144;
  public int JJTDELETEDATA = 145;
  public int JJTDELETEWHERE = 146;
  public int JJTDELETECLAUSE = 147;
  public int JJTINSERTCLAUSE = 148;
  public int JJTMODIFY = 149;


  public String[] jjtNodeName = {
    "UpdateSequence",
    "UpdateContainer",
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "FromNamedWindow",
    "Window",
    "TimeUnit",
    "WindowOverlap",
    "LogicalWindow",
    "PhysicalWindow",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "DatasetClause",
    "WhereClause",
    "WindowInWhereClause",
    "BindingsClause",
    "InlineData",
    "BindingSet",
    "BindingValue",
    "GroupClause",
    "OrderClause",
    "GroupCondition",
    "HavingClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "MinusGraphPattern",
    "ServiceGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "TriplesSameSubjectPath",
    "PropertyListPath",
    "PathAlternative",
    "PathSequence",
    "PathElt",
    "IRI",
    "PathOneInPropertySet",
    "PathMod",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Infix",
    "Math",
    "Not",
    "NumericLiteral",
    "Count",
    "Sum",
    "Min",
    "Max",
    "Avg",
    "Sample",
    "GroupConcat",
    "MD5",
    "SHA1",
    "SHA224",
    "SHA256",
    "SHA384",
    "SHA512",
    "Now",
    "Year",
    "Month",
    "Day",
    "Hours",
    "Minutes",
    "Seconds",
    "Timezone",
    "Tz",
    "Rand",
    "Abs",
    "Ceil",
    "Floor",
    "Round",
    "Substr",
    "StrLen",
    "UpperCase",
    "LowerCase",
    "StrStarts",
    "StrEnds",
    "StrBefore",
    "StrAfter",
    "Replace",
    "Concat",
    "Contains",
    "EncodeForURI",
    "If",
    "In",
    "NotIn",
    "Coalesce",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "IsNumeric",
    "BNodeFunc",
    "IRIFunc",
    "StrDt",
    "StrLang",
    "UUID",
    "STRUUID",
    "Bind",
    "RegexExpression",
    "ExistsFunc",
    "NotExistsFunc",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
    "GraphRefAll",
    "GraphOrDefault",
    "UnparsedQuadDataBlock",
    "QuadsNotTriples",
    "Load",
    "Clear",
    "Drop",
    "Add",
    "Move",
    "Copy",
    "Create",
    "InsertData",
    "DeleteData",
    "DeleteWhere",
    "DeleteClause",
    "InsertClause",
    "Modify",
  };
}
/* JavaCC - OriginalChecksum=287bdb6f6e58b4e810b8ccfd30826370 (do not edit this line) */
